/*
 * # Podcast Show Notes Architect
 * A flow that transforms raw podcast transcripts into publication-ready show notes,
 * complete with key takeaways, timestamped quotes, and a promotional social media thread.
 *
 * ## Purpose
 * This flow is responsible for eliminating the manual, time-consuming work of writing
 * podcast show notes. It accepts a raw transcript and optional metadata (podcast title,
 * episode number, host names, and guest names) from an API caller. It uses a structured
 * extraction stage to identify the episode's core narrative elements, key insights, and
 * quotable moments. It then synthesizes that structured data into two final outputs: a
 * complete, publication-ready show notes document and a ready-to-post social media thread.
 *
 * The outcome matters because high-quality show notes improve SEO discoverability, help
 * listeners quickly assess whether an episode is relevant, and serve as ready-made
 * promotional content — all tasks that typically take creators 60–90 minutes per episode.
 *
 * Within the wider system, this is a standalone entry-point flow with a two-stage
 * pipeline: structured extraction followed by narrative composition.
 *
 * ## When To Use
 * - Use when you have a complete or near-complete podcast transcript and need show notes fast.
 * - Use when you want to extract key insights in a structured, machine-readable format first.
 * - Use when you need both a long-form show notes document AND a short social media thread.
 * - Use when the transcript already exists as plain text (not an audio file).
 *
 * ## When Not To Use
 * - Do not use when the transcript is missing or only a topic/title has been provided.
 * - Do not use when the source is an audio file that has not been transcribed.
 * - Do not use when model configuration for either LLM node has not been supplied.
 * - Do not use when you only want one of the outputs (both are generated by the same flow).
 *
 * ## Inputs
 * | Field | Type | Required | Description |
 * |---|---|---|---|
 * | `transcript` | `string` | Yes | Full raw text of the podcast episode transcript. |
 * | `podcast_title` | `string` | No | The name of the podcast show (e.g., "The Lex Fridman Podcast"). |
 * | `episode_number` | `string` | No | The episode number or identifier (e.g., "Episode 421"). |
 * | `guest_names` | `string` | No | Names of guests featured in the episode, comma-separated. |
 * | `host_names` | `string` | No | Names of the host(s), comma-separated. |
 *
 * ## Outputs
 * | Field | Type | Description |
 * |---|---|---|
 * | `show_notes` | `string` | Publication-ready show notes document with episode summary, key takeaways, and timestamped quotes. |
 * | `social_thread` | `string` | A ready-to-post multi-part Twitter/LinkedIn promotional thread for the episode. |
 *
 * ## Dependencies
 * ### Upstream Flows
 * This flow is a standalone entry-point flow. No other Lamatic flow must run before it.
 * The transcript must exist as plain text before invocation.
 *
 * ### External Services
 * - Lamatic API trigger runtime — receives inbound API requests.
 * - Instructor-compatible text generation model — used by `Extract Structure` for constrained JSON output.
 * - Chat/text generation model — used by `Generate Show Notes` and `Generate Social Thread`.
 *
 * ### Environment Variables
 * - No explicit environment variables declared in this flow source.
 * - Model provider credentials are required by the configured model configurations.
 *
 * ## Node Walkthrough
 * 1. `API Request` (`graphqlNode` trigger) — Receives the transcript and optional metadata.
 * 2. `Extract Structure` (`InstructorLLMNode`) — Extracts episode summary, top 5 takeaways, and top 3 quotable moments with timestamps as structured JSON.
 * 3. `Generate Show Notes` (`LLMNode`) — Synthesizes structured JSON into a polished, publication-ready show notes document.
 * 4. `Generate Social Thread` (`LLMNode`) — Synthesizes structured JSON into a punchy multi-part social media thread.
 * 5. `API Response` (`graphqlResponseNode`) — Returns both `show_notes` and `social_thread` to the caller.
 *
 * ## Error Scenarios
 * | Symptom | Likely Cause | Recommended Fix |
 * |---|---|---|
 * | Show notes are generic or empty | Transcript was too short or lacked clear insights | Provide a fuller transcript with actual dialogue |
 * | Timestamps are missing or wrong | Transcript has no timestamp markers | Add [MM:SS] markers to transcript before submission, or accept natural-language references |
 * | JSON extraction fails | InstructorLLMNode misconfigured | Verify `InstructorLLMNode` model config and schema settings |
 * | Social thread tone is wrong | The composition prompt was not calibrated | Tune `generate-social-thread_system.md` prompt for desired platform voice |
 * | Request fails at trigger | Missing required `transcript` field | Ensure payload includes `transcript` as a non-empty string |
 */

// Flow: podcast-show-notes-architect

// ── Meta ──────────────────────────────────────────────
export const meta = {
  "name": "Podcast Show Notes Architect",
  "description": "Transforms raw podcast transcripts into structured show notes and a promotional social media thread.",
  "tags": "podcast,content-creation,social-media,generative,automation",
  "testInput": "",
  "githubUrl": "https://github.com/Lamatic/AgentKit/tree/main/kits/podcast-show-notes-architect",
  "documentationUrl": "",
  "deployUrl": ""
};

// ── Inputs ────────────────────────────────────────────
export const inputs = {
  "InstructorLLMNode_101": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "mode": "instructor",
      "description": "Select the model to extract structured data from the transcript.",
      "modelType": "generator/text",
      "required": true,
      "isPrivate": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      }
    }
  ],
  "LLMNode_202": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "modelType": "generator/text",
      "mode": "chat",
      "description": "Select the model to generate publication-ready show notes.",
      "required": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      },
      "isPrivate": true
    }
  ],
  "LLMNode_303": [
    {
      "name": "generativeModelName",
      "label": "Generative Model Name",
      "type": "model",
      "modelType": "generator/text",
      "mode": "chat",
      "description": "Select the model to generate the promotional social media thread.",
      "required": true,
      "defaultValue": [
        {
          "configName": "configA",
          "type": "generator/text",
          "provider_name": "",
          "credential_name": "",
          "params": {}
        }
      ],
      "typeOptions": {
        "loadOptionsMethod": "listModels"
      },
      "isPrivate": true
    }
  ]
};

// ── References ────────────────────────────────────────
export const references = {
  "constitutions": {
    "default": "@constitutions/default.md"
  },
  "prompts": {
    "podcast_show_notes_architect_extract_structure_system": "@prompts/podcast-show-notes-architect_extract-structure_system.md",
    "podcast_show_notes_architect_extract_structure_user": "@prompts/podcast-show-notes-architect_extract-structure_user.md",
    "podcast_show_notes_architect_generate_show_notes_system": "@prompts/podcast-show-notes-architect_generate-show-notes_system.md",
    "podcast_show_notes_architect_generate_show_notes_user": "@prompts/podcast-show-notes-architect_generate-show-notes_user.md",
    "podcast_show_notes_architect_generate_social_thread_system": "@prompts/podcast-show-notes-architect_generate-social-thread_system.md",
    "podcast_show_notes_architect_generate_social_thread_user": "@prompts/podcast-show-notes-architect_generate-social-thread_user.md"
  },
  "modelConfigs": {
    "podcast_show_notes_architect_extract_structure": "@model-configs/podcast-show-notes-architect_extract-structure.ts",
    "podcast_show_notes_architect_generate_show_notes": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts",
    "podcast_show_notes_architect_generate_social_thread": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts"
  }
};

// ── Nodes & Edges ─────────────────────────────────────
export const nodes = [
  {
    "id": "triggerNode_1",
    "data": {
      "modes": {},
      "nodeId": "graphqlNode",
      "values": {
        "id": "triggerNode_1",
        "nodeName": "API Request",
        "responeType": "realtime",
        "advance_schema": "{\n  \"transcript\": \"string\",\n  \"podcast_title\": \"string\",\n  \"episode_number\": \"string\",\n  \"guest_names\": \"string\",\n  \"host_names\": \"string\"\n}"
      },
      "trigger": true
    },
    "type": "triggerNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 0
    },
    "selected": true
  },
  {
    "id": "InstructorLLMNode_101",
    "data": {
      "label": "dynamicNode node",
      "modes": {},
      "nodeId": "InstructorLLMNode",
      "values": {
        "id": "InstructorLLMNode_101",
        "tools": [],
        "schema": "{\n  \"type\": \"object\",\n  \"properties\": {\n    \"episode_summary\": {\n      \"type\": \"string\",\n      \"required\": true\n    },\n    \"key_takeaways\": {\n      \"type\": \"array\",\n      \"items\": { \"type\": \"string\" }\n    },\n    \"quotable_moments\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"object\",\n        \"properties\": {\n          \"timestamp\": { \"type\": \"string\" },\n          \"speaker\": { \"type\": \"string\" },\n          \"quote\": { \"type\": \"string\" }\n        }\n      }\n    },\n    \"topics_covered\": {\n      \"type\": \"array\",\n      \"items\": { \"type\": \"string\" }\n    }\n  }\n}",
        "prompts": [
          {
            "id": "psna-extract-sys-001",
            "role": "system",
            "content": "@prompts/podcast-show-notes-architect_extract-structure_system.md"
          },
          {
            "id": "psna-extract-usr-001",
            "role": "user",
            "content": "@prompts/podcast-show-notes-architect_extract-structure_user.md"
          }
        ],
        "memories": "@model-configs/podcast-show-notes-architect_extract-structure.ts",
        "messages": "@model-configs/podcast-show-notes-architect_extract-structure.ts",
        "nodeName": "Extract Structure",
        "attachments": "@model-configs/podcast-show-notes-architect_extract-structure.ts",
        "generativeModelName": "@model-configs/podcast-show-notes-architect_extract-structure.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 130
    },
    "selected": false
  },
  {
    "id": "LLMNode_202",
    "data": {
      "label": "dynamicNode node",
      "modes": {},
      "nodeId": "LLMNode",
      "values": {
        "id": "LLMNode_202",
        "tools": [],
        "prompts": [
          {
            "id": "psna-shownotes-sys-001",
            "role": "system",
            "content": "@prompts/podcast-show-notes-architect_generate-show-notes_system.md"
          },
          {
            "id": "psna-shownotes-usr-001",
            "role": "user",
            "content": "@prompts/podcast-show-notes-architect_generate-show-notes_user.md"
          }
        ],
        "memories": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts",
        "messages": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts",
        "nodeName": "Generate Show Notes",
        "attachments": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts",
        "credentials": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts",
        "generativeModelName": "@model-configs/podcast-show-notes-architect_generate-show-notes.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 260
    },
    "selected": false
  },
  {
    "id": "LLMNode_303",
    "data": {
      "label": "dynamicNode node",
      "modes": {},
      "nodeId": "LLMNode",
      "values": {
        "id": "LLMNode_303",
        "tools": [],
        "prompts": [
          {
            "id": "psna-social-sys-001",
            "role": "system",
            "content": "@prompts/podcast-show-notes-architect_generate-social-thread_system.md"
          },
          {
            "id": "psna-social-usr-001",
            "role": "user",
            "content": "@prompts/podcast-show-notes-architect_generate-social-thread_user.md"
          }
        ],
        "memories": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts",
        "messages": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts",
        "nodeName": "Generate Social Thread",
        "attachments": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts",
        "credentials": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts",
        "generativeModelName": "@model-configs/podcast-show-notes-architect_generate-social-thread.ts"
      }
    },
    "type": "dynamicNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 390
    },
    "selected": false
  },
  {
    "id": "responseNode_triggerNode_1",
    "data": {
      "label": "Response",
      "nodeId": "graphqlResponseNode",
      "values": {
        "id": "responseNode_triggerNode_1",
        "headers": "{\"content-type\":\"application/json\"}",
        "retries": "0",
        "nodeName": "API Response",
        "webhookUrl": "",
        "retry_delay": "0",
        "needs": [
          "LLMNode_202",
          "LLMNode_303"
        ],
        "outputMapping": "{\n  \"show_notes\": \"{{LLMNode_202.output.generatedResponse}}\",\n  \"social_thread\": \"{{LLMNode_303.output.generatedResponse}}\"\n}"
      },
      "isResponseNode": true
    },
    "type": "responseNode",
    "measured": {
      "width": 216,
      "height": 93
    },
    "position": {
      "x": 0,
      "y": 520
    },
    "selected": false
  }
];

export const edges = [
  {
    "id": "triggerNode_1-InstructorLLMNode_101-001",
    "type": "defaultEdge",
    "source": "triggerNode_1",
    "target": "InstructorLLMNode_101",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "InstructorLLMNode_101-LLMNode_202-002",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_101",
    "target": "LLMNode_202",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "InstructorLLMNode_101-LLMNode_303-003",
    "type": "defaultEdge",
    "source": "InstructorLLMNode_101",
    "target": "LLMNode_303",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "LLMNode_202-responseNode_triggerNode_1-004",
    "type": "defaultEdge",
    "source": "LLMNode_202",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "LLMNode_303-responseNode_triggerNode_1-005",
    "type": "defaultEdge",
    "source": "LLMNode_303",
    "target": "responseNode_triggerNode_1",
    "sourceHandle": "bottom",
    "targetHandle": "top"
  },
  {
    "id": "response-trigger_triggerNode_1",
    "type": "responseEdge",
    "source": "triggerNode_1",
    "target": "responseNode_triggerNode_1",
    "selected": false,
    "sourceHandle": "to-response",
    "targetHandle": "from-trigger"
  }
];

export default { meta, inputs, references, nodes, edges };
